[package]
name = "lyred"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

chrono = "0.4"

midly = "0.5"
enigo = { git = "https://github.com/Ykong1337/enigo.git" }
anyhow = "1"
rayon = "1"

image = "0.24"
eframe = "0.20"
rfd = "0.10"
windows-hotkeys = "0.1"

[target.'cfg(target_os="windows")'.build-dependencies]
winres = "0.1"

[[bin]]
name = "lyred"
path = "src/lyred.rs"