[package]
name = "lyred"
version = "1.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
midly = "0.5"
rdev = "0.5"
windows-hotkeys = "0.2"
rayon = "1"
image = "0.24"
eframe = "0.22"
rfd = "0.11"
once_cell = "1"
portable-atomic = { version = "1", features = ["float"] }
font-kit = "0.11"

[target.'cfg(target_os="windows")'.build-dependencies]
winres = "0.1"

[profile.release]
lto = true