[package]
name = "lyred"
version = "1.0.75"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

chrono = "0.4"

midly = "0.5"
rdev = "0.5"
rayon = "1"

image = "0.24"
eframe = { version = "0.21", default-features = false, features = ["wgpu"] }
rfd = "0.11"
windows-hotkeys = "0.1"

[target.'cfg(target_os="windows")'.build-dependencies]
winres = "0.1"

[[bin]]
name = "lyred"
path = "src/lyred.rs"

[profile.release]
lto = true